# 路径配置
workflow_path: "product_image.json"
prompt_file: "CC.txt"
#filename_prefix: "刘思泽"

# 模型配置
checkpoint: "flux1-dev-fp8.safetensors"  # 主模型路径
lora_active_list: "lora_active_list.txt"  # LoRA模型集合
# lora_name: "FluxMythP0rtr4itStyle.safetensors"  # LoRA模型
seed_range: [ 1, 18446744073709551614 ]  # 随机种子范围

# 图像参数
#高清
#width: 1440
#height: 2560
width: 720
height: 1280
batch_size: 4
max_filename_length: 15

# 高级设置
max_retries: 3
request_timeout: 30
log_file: "generation_log.csv"
log_dir: "excel"