# 所属人
people: "李进"
# 图片文件夹路径
image_folder: "G:/Desktop"
batch_size: 4              # 每批数量
BiRefNet_url: "D:/ai/ComfyUI-aki-v1.6/ComfyUI/models/BiRefNet"
flux_Guide: 3.5
style_num: 4.5


# 高分辨率工作流模板
workflow: "print_workshop_advance.json"

seed_range: [1, 18446744073709551614]

# 网络设置
max_retries: 3             # 最大重试次数
request_timeout: 30        # 请求超时时间(秒)

# LORA模型集合
lora_names:
  - "ral-dissolve-flux.safetensors"
  - "Contemporary_Zodiac_Sculpture.safetensors"
  - "Dark_Ghibli.safetensors"
  - "Defluxion II.safetensors"
  - "FluxMythP0rtr4itStyle.safetensors"
  - "Hyper_detailed_illustrationFlux.safetensors"
  - "ral-dissolve-flux.safetensors"
  - "玻璃破碎.safetensors"
  - "麦橘超中国风插画.safetensors"
  - "fire2.safetensors"
  - "letters-000001.safetensors"
  - "OB国风绘画V2.safetensors"
  - "fire2.safetensors"
  - "传统中国画.safetensors"
  - "油画风格.safetensors"
  - "字体设计.safetensors"
  - "EtherealHuman.safetensors"
  - "HyperdetailedRealismMJ7Flux.safetensors"
  - "Paperfold_Style_FLUX-_Make_folded_paper_objects_animals_and_humans.safetensors"
  - "墙面艺术.safetensors"
  - "传统中国画.safetensors"
  - "蒙娜丽莎.safetensors"
  - "ArsMJStyle.safetensors"
  - "j_gongbihua_flux_rank2_bf16.safetensors"
  - "Tartarus_-_2.0-000012.safetensors"
  - "gilelvgren1_d8a4e9a.safetensors"
  - "FluxMythR3alism.safetensors"
  - "Disney_Style.safetensors"
  - "Niji_semi-realism_flux.safetensors"
  - "像素风_日系_抖音热门风格_v1.0.safetensors"
  - "创意排版.safetensors"
  - "tarot-8-funnycaptionshort.safetensors"
  - "EmoticonFlux.safetensors"
  - "垃圾摇滚.safetensors"
  - "X梵高油画风格Van Gogh style-flux-lora-000006.safetensors"
  - "Graffiti_Logo_Style_Flux.safetensors"
  - "logomaker1024-000008.safetensors"
  - "CuteLogoMaker.safetensors"
  - "Retro_Logo_Style_Flux.safetensors"


